name: Build and release RPM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends \
          build-essential \
          git \
          libpcap-dev \
          libvirt-dev \
          libnfnetlink-dev \
          libxml2-dev \
          libssl-dev \
          libdbus-1-dev
          
    - name: make
      run: make rpm FEATURES="PCAP TCP DROPMON DBUS SYSTEMD NFLOG HOST"
      
    - name: GET VERSION
      run:  echo "MYVER=`./getVersion`" >> $GITHUB_ENV 
      
    - name: GET ARCH
      run: echo "MYARCH=`uname -m`" >> $GITHUB_ENV 
      
    - name: Get RELEASE
      run: echo "MYREL=`./getRelease`" >> $GITHUB_ENV 

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.MYVER }}
        release_name: Release ${{ env.MYREL }}
        draft: false
        prerelease: false
        
    - name: Upload standard release asset
      id: upload-release-asset-1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hsflowd-${{ env.MYVER }}-${{ env.MYREL }}.${{ env.MYARCH }}.rpm
        asset_name: hsflowd-${{ env.MYVER }}-${{ env.MYREL }}.${{ env.MYARCH }}.rpm
        asset_content_type: application/octet-stream
 
